### ISSUE TITLE
File path is file name

### ISSUE THREAD

**Issue by huntermetts** [react-dropzone/file-selector#22]
Hello!

I am attempting to take a docx file and convert it into a pdf.
In order to do that I need the uploaded/"dropped" file path as the function's first parameter.

When I console.log the file object's path it just returns the name. Any recommendations?

Thanks.

<img width="642" alt="Screen Shot 2019-12-16 at 8 10 26 AM" src="https://user-images.githubusercontent.com/44845206/70913393-8c474000-1fdb-11ea-8ff7-5471c9bd3544.png">

**Comment by rolandjitsu** [comment]
Please provide a codesandbox or something that illustrates the issue. And please provide the platform, browser, etc.

**Comment by 0x111** [comment]
Based on the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) api docs

> Important note: FileReader is used to read file content from the user's (remote) system in secure ways only. It cannot be used to simply read a file by pathname from a file system. To read files by pathname in JavaScript, standard Ajax solutions should be used to do server-side file reading, with CORS permission if reading cross-domain.

So that is probably why you are not getting a full filepath and instead of that only a filename as such. If you wan't to read the contents of a file, I recommend using the FileReader api.

So if I would've wanted to read the contents of file as an ArrayBuffer, I would use something like this:
```javascript
const reader = new FileReader();
reader.onload = () => {
    // Do whatever you want with the file contents
    const binaryStr = reader.result;
};
reader.readAsArrayBuffer(file);
```
You can find more examples of this on the FileReader docs. 
This way you would not need the full path to the file at all and you sitll would've all the contents.

**Comment by rolandjitsu** [comment]
Gonna close this now.
